import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/header";
import { TopicContent } from "@/components/topic/content";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <TopicContent />
      </main>
    </>
  );
};

export default Home;
